name: github pages

on:
  push:
    branches:
      - hugo

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.75.1'
          extended: true

      - name: Build
        run: hugo --gc --minify --cleanDestinationDir

      # - name: Feed Fix
      #   run: cp ./public/posts/feed.xml ./public/feed.xml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.3.2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: manuss20/manuss20.github.io
          publish_dir: ./public
          user_name: manuss20
          user_email: manuss20@gmail.com
          publish_branch: master